### ISSUE TITLE
Desconexão 

### ISSUE THREAD

**Issue by samuel1992** [ettoreleandrotognoli/python-ami#10]
Amigo, estou usando sua lib. Quando tenho muitos eventos reparo que ela desconecta do ami, mas não me retorna nenhum exception no uso dos filtros etc.

**Comment by ettoreleandrotognoli** [comment]
Você pode passar mais informações?
Qual a versão da lib que você está usando?
Tem como fazer um debug do AMI para eu ter uma noção da quantidade de eventos?

**Comment by samuel1992** [comment]
Opa, estou usando a versão 0.1.1 da lib. Quanto a o debug do AMI, como quer que eu faça? Te mando um arquivo com todos eventos simulando uma parada?

**Comment by ettoreleandrotognoli** [comment]
Eu não lembro o que eu arrumei da versão 0.1.1 até a 0.1.5 de cabeça, se você puder atualizar e ver se o erro persiste pode ajudar
Um arquivo com o eventos próximo ao momento de parada seria ótimo

**Comment by samuel1992** [comment]
Opa, pode deixar, vou atualizar aqui. Não sabia que tinha uma nova versão, instalei pelo pip.

**Comment by samuel1992** [comment]
Opa, aparentemente corrigiu o problema atualizando. Caso eu encontre alguma coisa volto a reportar. Obrigado pela lib, excelente trabalho!
