### ISSUE TITLE
Not seeing any events with simple_event_notification.py

### ISSUE THREAD

**Issue by jsooter** [ettoreleandrotognoli/python-ami#12]
I see a successful connection in the asterisk console but no events are printed to the screen. There are also no errors. I have the same problem in other scripts which are similar.

Python 3.4.2
Asterisk 14.6.2

**Comment by ettoreleandrotognoli** [comment]
Wich version of python-ami are you using?

**Comment by ettoreleandrotognoli** [comment]
The simple event notification is using the notify-send command, It doesn't print anything on console.
When you run "notify-send title body" on the console does a window appear?  If It doesn't, the example wont work in your machine
