### ISSUE TITLE
how to use even's result to programing with List

### ISSUE THREAD

**Issue by RyanDuong** [ettoreleandrotognoli/python-ami#13]
Dear Author,

I would like to thanks your wonderful library, I doing small project with python2.7 combine asterisk-ami 0.1.5. I can see the even but can not use it like List can you help me
for example:
**1- print(event)** >>> Event : Newexten -> {u'Context': u'ext-did', u'Priority': u'9', u'Func': u'pbx_extension_helper', u'SequenceNumber': u'14026', u'Uniqueid': u'1508071217.86', u'Extension': u's', u'Application': u'Goto', u'File': u'pbx.c', u'Privilege': u'dialplan,all', u'Line': u'4738', u'AppData': u'ext-queues,9002,1', u'Channel': u'SIP/0979960842-00000056'}
**2- print list** >>> [<asterisk.ami.event.Event object at 0x00000000028F86A0>]

Thanks a lot

**Comment by ettoreleandrotognoli** [comment]
With python2.7 I think it works:
```python
print map(str,event_list)
```

**Comment by RyanDuong** [comment]
thanks your reply, I had try to use map but something strange
print map(str,event_list) 
-> 
['Member', 'Func', 'SequenceNumber', 'MemberName', 'Uniqueid', 'Queue', 'Reason', 'File', 'Privilege', 'Line', 'HoldTime', 'Channel', 'TalkTime']
**it just display Name of event  not see any more**

**Comment by ettoreleandrotognoli** [comment]
I thinks taht is printing the event keys, Uniqueid not is a event name.
Do you sure the event_list is a iterable of events?

**Comment by RyanDuong** [comment]
thanks your reply, that my mistake. I can controll it with list and map, now . Thank again
