### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by scuba323** [ettoreleandrotognoli/python-ami#14]
Hello! I am still learning python, but I ran  
`pip install asterisk-ami`  
and tried the code in the README.md page, but I still get  
`  
File "/home/scuba323/lulpy/asterisk.py", line 8, in <module>  
    from asterisk.ami import AMIClient  
ImportError: No module named ami`

**Comment by ettoreleandrotognoli** [comment]
Sorry, I couldn't reproduce the problem
Can you give more information about your problem?
Opeation System, python version, asterisk-ami version can help

**Comment by stripcode** [comment]
He called the file asterisk.py.
I got the same problem :)
It's not your fault

**Comment by ettoreleandrotognoli** [comment]
It's becomes obvious now what happened, thanks!
