### ISSUE TITLE
Problem with event handling

### ISSUE THREAD

**Issue by user1831** [ettoreleandrotognoli/python-ami#15]
My code:

```
from asterisk.ami import AMIClient
from asterisk.ami import SimpleAction
 
client = AMIClient(address='127.0.0.1',port=5038)
client.login(username='username',secret='password')
 
def event_listener(event,**kwargs):
	print(event)
 
client.add_event_listener(event_listener, white_list=['EndpointDetail'])
 
action = SimpleAction(
            'PJSIPShowEndpoint',
            Endpoint='test'
        )
 
res = client.send_action(action).response
 
print(event)
```

How to access the response at `print(event)`? I want to access the returned data in the main thread.

**Comment by adeshpandey** [comment]
addEventListener does not catch all the events in the successful action, I am initiating Originate action but none of the events is caught in the case of a successful dial and action exits without waiting for the hangup event in the synchronous call.

**Comment by ettoreleandrotognoli** [comment]
I don't know what is the problem,
can you show some code?

**Comment by romkazor** [comment]
@adeshpandey No, that's not how it works. For hangup you can catch event Hangup.
Close this.
