### ISSUE TITLE
listen to event stuck when server goes off

### ISSUE THREAD

**Issue by alirezaimi** [ettoreleandrotognoli/python-ami#16]
Hi
when asterisk server goes off and on again i must restart event listener because event listener do not get events any more until stop and start it again .
1- how can i debug it ?
2- how can i solve this problem ?!

**Comment by ettoreleandrotognoli** [comment]
I dislike the solution ( I want to rafactor), but did you try to use the AutoReconnect?
 has an example in [mqtt_bridge](https://github.com/ettoreleandrotognoli/python-ami/blob/master/examples/mqtt_bridge.py).
I don't know o good way to debug it, but I tested the AutoReconnect disconnecting the network, turning off the server and closing the ssh bridge.

**Comment by alirezaimi** [comment]
Hi
Thanks for your support, this module so good that solved so many of my problem with cdr log ! 
very thank for that.
I test AutoReconnect, i hope this solve my problem ...
