### ISSUE TITLE
New version with Python3.7 compatibility

### ISSUE THREAD

**Issue by yair-voca** [ettoreleandrotognoli/python-ami#42]
Hi,
I Need new version with Python3.7 compatibility, 
I saw that you already pushed a fix with Python3.7 compatibility.
**Could you please release a new version including the Python3.7 compatibility?**

Thanks.

**Comment by ettoreleandrotognoli** [comment]
Hello,
I'm not working with this library recently or with any kind of PABX.
I don't know when I'll have time to update the library.

Sorry =(

**Comment by yair-voca** [comment]
Thanks for the fast response.
