### ISSUE TITLE
username and secret？？？

### ISSUE THREAD

**Issue by Chenny0808** [ettoreleandrotognoli/python-ami#43]
client.login(username='username',secret='password')
what is username and secret？

**Comment by ettoreleandrotognoli** [comment]
Username and secret are necessary to authenticate, I put some references bellow, I hope that it would be clear now
https://wiki.asterisk.org/wiki/display/AST/Asterisk+17+ManagerAction_Login
https://www.voip-info.org/asterisk-manager-api-action-login/
https://www.voip-info.org/asterisk-manager-example-login/
