### ISSUE TITLE
default timeout on socket is only 3 seconds. It is too small. 

### ISSUE THREAD

**Issue by radetsky** [ettoreleandrotognoli/python-ami#47]
I spend 8 hours finding why my python script simple_event_notification.py from example did not work. 
Spoiler: It is disconnected on time out because the test asterisk does not send any event. 
I firewalled it from remote unneeded activity.  

I suggest setting it to a bigger value.

**Comment by ettoreleandrotognoli** [comment]
Hello, sorry for your 8 hours =/
Are you suggesting changing the [default value](https://github.com/ettoreleandrotognoli/python-ami/blob/dea9d37bf0fd881205eefaa0d0d9095834ed0117/asterisk/ami/client.py#L58), or setting a bigger value only on the example?
