### ISSUE TITLE
'utf-8' codec can't decode byte: invalid continuation byte

### ISSUE THREAD

**Issue by jellex** [ettoreleandrotognoli/python-ami#7]
Hello 0/

My problem like Issue #3, but other error: on console I received error
> utf-8' codec can't decode byte 0xd1 in position 146: invalid continuation byte

The fact is that my db contains values in latin-1 encoding.
I found the problem [here](https://github.com/ettoreleandrotognoli/python-ami/blob/master/asterisk/ami/client.py#L101). Yet I solved the problem so
```python
# yield pack.decode('utf-8')
yield pack.decode('latin-1')
```

As a solution to propose to establish the value of the encoding parameter, which could be given when creating an instance AMIClient or do something like
```python
try:
    yield pack.decode('utf-8')
except UnicodeDecodeError:
    yield pack.decode('latin-1')
```

Example of part byte received from asterisk:
`b'CallerIDName: \xc2\xe8\xf2\xe0\xeb\xe8\xe9 \xca\xe0\xeb\xe8\xed\xe8\xed'`

**Comment by ettoreleandrotognoli** [comment]
Hello! Thanks for your contribution!
I believe [this](https://github.com/ettoreleandrotognoli/python-ami/commit/c2de6399723f5cab32e4fc9f90f7426ebf1cf6a1) will solve your problem.

**Comment by jellex** [comment]
Yeah, it solve my problem.
Thank You very much
