### ISSUE TITLE
SimpleAction Import

### ISSUE THREAD

**Issue by ctrom** [ettoreleandrotognoli/python-ami#8]
I was unable to import SimpleAction until I added a reference to it on [line 6 of client.py](https://github.com/ettoreleandrotognoli/python-ami/blob/master/asterisk/ami/client.py#L6).

**Comment by ettoreleandrotognoli** [comment]
Did you try to import this way "from asterisk.ami.action import SimpleAction"?

**Comment by ctrom** [comment]
No, I was using `from asterisk.ami import SimpleAction` since that was the method recommended in the README.

**Comment by ettoreleandrotognoli** [comment]
You are right, I forgot the doc.
I will change the doc or do your suggestion.
Thanks!

**Comment by ettoreleandrotognoli** [comment]
Solved at [tag 0.1.2](https://github.com/ettoreleandrotognoli/python-ami/tree/0.1.2)
