### ISSUE TITLE
Error "None" ao processar duas funções de 5 em 5 segundos

### ISSUE THREAD

**Issue by flpmarcos** [ettoreleandrotognoli/python-ami#9]
Conforme informado no site, estou abrindo um issue para o meu problema.

Tenho duas funções que atualizam de 5 em 5 segundos, uma atualiza as ligações para o agente e a outra atualiza as filas do agente, estou criando um modulo de agente no asterisk, geralmente tenho esse erro ao enviar a ACTION, trava o servidor e no log printa uma mensagem "None" que só retorna após reiniciar o servidor porém ao reinicia-lo as requisições ficam na fila e ao enviar as requisições atrasadas da fila as vezes ele dá esse erro de novo as vezes não, monitoro com base em meus print's no código e os erros no arquivo log porém não aparece nada neles por isso criei os PRINT's, ambas as funções são chamadas por AJAX e o retorno eu monto um JSON para apresentar na tela.

Obs: A lib foi instalada com o pip porém creio que seja a versão mais atual.

Segue as duas funções abaixo:

def atualizaAgentQueue():
    
    print 'Processando...'
    
    print 'Obtendo nome do agente'
 
    member = 'Comercial'
    print 'Logando no servidor'
    client = AMIClient(address='x.x.x.x',port=5038)
    login = client.login(username='username,secret='userpass')
    
    print login.response
    
    #verificando se login obteve erro
    if login.response.is_error():
        raise Exception(str(login.response))
   
    adapter = AMIClientAdapter(client)
    
    end = threading.Event()
    agents = []
    params = []

    # recebe os eventos de PeerEntry
    def add_agent_listener(event, **kwargs):
        agents.append(event)
    
    # recebe os eventos 
    def add_params_listener(event, **kwargs):
        params.append(event)
    
    # recebe o evento 
    def end_agent_listener(event, **kwargs):
        end.set()
    actionId = uuid.uuid1().hex
    add_listener = client.add_event_listener(on_QueueMember=add_agent_listener, ActionID=actionId)
    add_listener2 = client.add_event_listener(on_QueueParams=add_params_listener, ActionID=actionId)
    end_listener = client.add_event_listener(on_QueueStatusComplete=end_agent_listener, ActionID=actionId)
    print 'Ativando Action'
    #filtro membro por fila 
    future = adapter.QueueStatus(Member=member,ActionID=actionId)
    print future.response
    # aguarda o PeerlistComplete
    end.wait()
    client.remove_event_listener(add_listener)
    client.remove_event_listener(add_listener2)
    client.remove_event_listener(end_listener)
    fila = '{"fila":['
    for agent in agents:    
        for param in params:
            if param['Queue'] == agent['Queue']:
              fila +='{"Queue":'+param['Queue']
              fila +=',"Abandoned":'+param['Abandoned']
              fila +=',"Wait":'+param['Calls']
              fila +=',"Holdtime":'+param['Holdtime']+'},'
    fila += ']}'
    fila = json.dumps(fila).replace("'",'"').replace(",]","]")
    fila = json.loads(fila)
    print("Finalizando Thread ...")
    end.clear()
    print 'Processo Finalizado'
    client.logoff()   
    return response.json(fila)
    

 
def atualizaAgentCall():
    
    print 'Processando...'
    
    ramal = 1016
    
    print 'Recebendo parametros'
      
     print 'Logando no servidor'
    client = AMIClient(address='x.x.x.x',port=5038)
    login = client.login(username='username,secret='userpass')
    
    adapter = AMIClientAdapter(client)
    
    end = threading.Event()
    calls = []
    
    # recebe os eventos de PeerEntry
    def add_call_listener(event, **kwargs):
        calls.append(event)
    # recebe o evento de PeerlistComplete
    def end_call_listener(event, **kwargs):
        end.set()
    
    actionId = uuid.uuid1().hex
    
    add_listener = client.add_event_listener(on_CoreShowChannel=add_call_listener, ActionID=actionId)
    
    end_listener = client.add_event_listener(on_CoreShowChannelsComplete=end_call_listener, ActionID=actionId)
    
    print 'Chamando action'

    #filtro membro por fila 
    future = adapter.CoreShowChannels(ActionID=actionId)
    print future.response
    
    # aguarda o PeerlistComplete
    end.wait()
    
    client.remove_event_listener(add_listener)
    client.remove_event_listener(end_listener)
    
    print 'Atribuindo e filtrando ligações'
    
    fila = '{'
    for call in calls:                               
        print call
        if ramal == call['CallerIDNum'] :
            fila += '"canal":' +'"'+ call['Channel'] +'"'+','
            fila += '"numero":' +'"'+ call['ConnectedLineNum'] +'"'+','
            fila += '"duracao":' +'"'+ call['Duration'] +'"'                   
    fila += '}'
    
    fila = json.dumps(fila).replace("'",'"').replace(",]","]")
    fila = json.loads(fila)
    print("Finalizando Thread ...")
    end.clear()
    print 'Processo Finalizado.'
    client.logoff()
    return response.json(fila)

**Comment by ettoreleandrotognoli** [comment]
Eu tive um problema uma vez por abrir e fechar conexões muitas vezes. O servidor com o AMI ficava com muitos sockets no estado "CLOSE_WAIT" e acabava estourando o limite de sockets. Acredito que possa ser esse seu problema também.
Você pode tentar alterar o limite do servidor ou reutilizar as conexões no seu cliente ([Pool de Conexões](https://pt.wikipedia.org/wiki/Pool_de_conex%C3%B5es)).

Para ver se é isso mesmo rode o comando:
netstat -ton | grep CLOSE_WAIT
no servidor para ver se tem os sockets mesmo.

**Comment by flpmarcos** [comment]
Acabei de logar no painel de Agente e entrar no servidor Asterisk, vejo inumeras conexões com esse status vindo do meu IP.
Se estourou assim, imagina uma empresa pode ter 20 PA's ou seja 20 agentes logados fazendo essa atualização de 5 em 5 segundos.

Problema que AMI não da para user websocket não é ?

**Comment by ettoreleandrotognoli** [comment]
Não vi nada com websocket ainda.
Pelo que entendi o AMI não foi projetado para receber tantas conexões como um servidor web.
Por isso quando tive esse problema resolvi com o Pool de Conexões.

**Comment by flpmarcos** [comment]
Errei ao passar uma informação, ele abre várias conexões porém elas ficam no estado TIME_WAIT.

Vou estudar um pouco sobre esse Pool de Conexões e tentar implementar em meu projeto.

**Comment by ettoreleandrotognoli** [comment]
Pelo que sei são estados semelhantes, são conexões que foram fechadas mas ficam aguardando para serem reutilizadas, mas o AMI nunca reutiliza.
Para fazer meu Pool de conexões eu usei uma lib que fiz de injeção de dependência [PyCDI](https://github.com/ettoreleandrotognoli/python-cdi) espero que ajude.

**Comment by flpmarcos** [comment]
Muito obrigado pela ajuda! sua biblioteca tem me ajudado muito em meu projeto.
